removeListener requires target and method to teardown
ERROR: Uncaught Error: Assertion Failed: You must pass at least an object, event name, and method or target and method/method name to removeListener